# Utiliser l'image officielle Node.js 18
FROM node:18

# Créer et changer vers le répertoire de l'application
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances de l'application
RUN npm install

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev"]