name: Check Branch Name

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check branch name
        run: |
          branch_name=${{ env.branch_name }}
          echo "Checking branch name: $branch_name"
          
          if [[ "$branch_name" == "main" ]]; then
            echo "Skipping branch name check for the 'main' branch."
            exit 0
          fi
          
          if [[ ! "$branch_name" =~ ^(feature|bugfix|hotfix)/ ]]; then
            echo "Invalid branch name '$branch_name'. It must start with 'feature/', 'bugfix/', or 'hotfix/'."
            exit 1
          fi
