name: Commit Message Check

on:
  push:
    branches:
      - 'feat-*'

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit message format
        run: |
          # Récupérer le message du dernier commit
          commit_message=$(git log -1 --pretty=%B)
          
          # Définir le format requis pour le message de commit
          required_format="^feat\([a-zA-Z0-9_-]+\): .+ #\d+$"
          
          # Vérifier si le message de commit correspond au format requis
          if ! [[ "$commit_message" =~ $required_format ]]; then
            echo "Le message de commit ne respecte pas le format requis."
            echo "Format requis : feat(nom_de_la_feature): description_du_commit #123"
            echo "Exemples :"
            echo "  feat(authentication): ajouter la fonctionnalité de connexion #123"
            echo "  feat(search): améliorer la recherche par mot-clé #456"
            exit 1
          fi
